version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - symfony_network
    environment:
      DATABASE_URL: "mysql://root:root@database:3306/admini?serverVersion=8.0.32&charset=utf8mb4"

  database:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admini
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - symfony_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  symfony_network:


volumes:
  db_data:


