version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - symfony_network
    environment:
      DATABASE_URL: "postgresql://root:root@database:5433/admini?serverVersion=15&charset=utf8"

  database:
    image: postgres:15
    container_name: symfony_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: admini
    ports:
      - "5433:5432"
    networks:
      - symfony_network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  symfony_network:


volumes:
  db_data:


